# Generated by Django 3.2 on 2021-04-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='date_joined',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date_joined',
            new_name='date_added',
        ),
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('answer_id', 'profile_id')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('question_id', 'profile_id')},
        ),
    ]
